### ISSUE TITLE
Replace most String-returning methods with Display impls

### ISSUE THREAD

**Issue by clarfon** [open-i18n/rust-unic#169]
In #168 I found just two different methods named `display` which simply call `format!` to return a string. The `Display` impl then simply prints this allocated string.

Instead of doing this, we should put the necessary formatting into a `Display` impl and let the user call `to_string` if the want a string version. There can even be `Into<String>` impls if necessary. This avoids unnecessary allocations, and also brings us closer to having a more allocation-free API.

I've noticed a lot of unnecessary allocations in this library and this would be an easy way to fix that.

**Comment by CAD97** [comment]
This directly pertains to discussion in #168 but I'm going to put it here because it fits here better.

All of these were found via IntelliJ IDEA's project-wide search. All searching was done over the `unic` directory exclusively, and test code results were manually excluded.

A list defined fn returning `String` (in the `unic` directory, excluding tests, full path to impl):

- `unic_idna::process::processing(&str, Flags, &mut Vec<Error>) -> String`
- `unic_ucd_age::age::Age::human(&self) -> String`
- `unic_ucd_core::UnicodeVersion::display(&self) -> String`
- `unic_ucd_name::name::Name::to_string(&self) -> String`
- `unic_ucd_normal::canonical_combining_class::CanonicalCombiningClass::display(&self) -> String`

A list of defined fn (not impls of traits) using the `human` moniker, excluding those above:

- `unic_char_property::property::CharProperty::prop_human_name() -> &'static str`
- `unic_char_property::range_types::EnumeratedCharProperty::human_name(&self) -> &'static str`
- `unic_char_property::range_types::BinaryCharProperty::human_name(&self) -> &'static str`

So, @behnam, here's my logic:

The `-> String` fn excluding `idna::processing` (that are replaced via `impl Display` and `ToString::to_string` in #168) should go. They are better expressed in terms of a non-allocating `Display::fmt` and the automatic `ToString::to_string` impl. However, the `human_name` fn that return `&'static str` are still useful even in face of a `Display::fmt` implementation that just uses the `human_name`: `human_name` is a non-allocating `&'static str` that describes the property. It is not the same case as the smattering of fake-`ToString::to_string` that we have collected, which add nothing of significant use.

So my approach: rework #168 a bit to just remove the fake-`ToString::to_string` fn. Consider if `idna::processing` can be expressed in a different manner, or at least as a `Cow<str>`. Keep the `Property::human_name` fn, as they provide useful semantic information about the property.

**Comment by clarcharr** [comment]
Sounds good to me! In general, methods returning `&'static str` are still very useful, as their returned strings are essentially "free," but anything that requires rendering should be kept in a `Display` impl.

**Comment by behnam** [comment]
I think I agree with most of what's proposed here. But there are situations that we cannot solve with only using `trait Display`.

Basically, any property value in UCD has at least two string representations: *abbr name* and *long name*. We have also added a user-friendly representation to this list: *human name*.

As it's shown in the list, `Age` property is kind of special (called `Custom` in the taxonomy). It does not have (and is not expected to have) a `'static &str` representation for all the values, because it's internally `UnicodeVersion`, which is all numeric values. Any string representation of these values would need string formatting, therefore requiring either a string formatter, or allocation.

So, basically we need to decide if we want to go with a string formatter in all situation, instead of allocation. If so, it's fine, and we can do that, and even add the method definition to the traits. So, `Enumerated` trait will return `'static &str` from `abbr_name()`, but the same method on `Custom` will take a string formatter.

Another matter is to merge the `human_name()` method with `Display::fmt()`. Assuming that we implement `human_name()` with a string formatter, do you still want to merge them, or can we just inline it?

If we're keeping *human* title for that naming in general, then I prefer the explicitly naming the functions, so for the example of `Age` values, we will have all three of `abbr_name()`, `long_name()` and `human_name()`, all with a similar API, and *human* being the default *Display* representation.

----

Agreed that `idna::processing` is a different matter, which we want to discuss in <https://github.com/behnam/rust-unic/issues/6>. I already have some ideas, but we cannot implement before having some string-level algorithms ready to put in use there.

**Comment by CAD97** [comment]
I think the only thing we're not in full agreement on is `CustomProperty`/`Age`?

Correct me if I'm wrong, but the actions here are:

- Replace current `::human` `::display`, and `::to_string` fn that return `String` with just the `impl Display`
- Figure out what kind of `abbr_name`, `long_name`, and `human_name` contract we want to guarantee on `CustomProperty`
- impl the `CustomProperty` version of the `abbr_name`, `long_name`, and `human_name` for `Age`

Notably:

- `EnumeratedCharProperty`/`BinaryCharProperty` `::human_name()` remains the same
- #168 can move forward just by removing the four fn that it's currently touching
- We don't have to decide `CustomProperty`'s `*_name()` fn and thus `Age`'s just yet. I filed #173 to cover that

**Comment by behnam** [comment]
Yeah, all sounds good, @CAD97!

@clarcharr, could you please prepare #168 to merge?

**Comment by behnam** [comment]
Is there any work left here? I believe we've everything covered now that most of them are in `no_std` mode.

**Comment by behnam** [comment]
I believe we're done here. Please feel free to re-open/re-file if there's more related work left.
